version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html
  - source: /services.html
    destination: /var/www/html
  - source: /booking.html
    destination: /var/www/html
  - source: /gallery.html
    destination: /var/www/html
  - source: /contact.html
    destination: /var/www/html
  - source: /css
    destination: /var/www/html
  - source: /js
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/dep.sh
      timeout: 300
      runas: root
